### ISSUE TITLE
auto_install.sh options error

### ISSUE THREAD

**Issue by johned0** [xmos/vocalfusion_3510_avs_setup#35] opened 2019-10-22 16:05 UTC
Help lists "-d" option :
  echo  '  -d <device-type>    XMOS device to setup: default xvf3510, possible value xvf3500'

But get opts handles "-x" :
        x )
            XMOS_DEVICE="$OPTARGS"

John

**Comment by DaveAtkinsonXMOS** [comment] 2020-11-12 11:29
This repo is to be discontinued so I am closing this issue. The issue is fixed in the new unified xmos/vocalfusion-avs-setup repo. Thanks.

**Closed by DaveAtkinsonXMOS** 2020-11-12 11:29 UTC
